# Generated by Django 4.2.13 on 2024-07-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                (
                    "pricingModel",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("business", "Business"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("button_text", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="accounts.plan",
                    ),
                ),
            ],
        ),
    ]
