# Generated by Django 4.2.13 on 2024-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("message", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
