# Generated by Django 4.2.13 on 2024-07-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "ContactUs", "verbose_name_plural": "ContactUs"},
        ),
        migrations.AlterField(
            model_name="plan",
            name="button_text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name="plan",
            name="pricingModel",
            field=models.CharField(max_length=100),
        ),
    ]
