# Generated by Django 4.2.13 on 2024-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_contactus_options_alter_plan_button_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(),
        ),
    ]
