# Generated by Django 4.2.13 on 2024-07-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_plan_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="subscription",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")], max_length=100
            ),
        ),
    ]
